server:
  address: 0.0.0.0:38080
  tls: server
client:
  address: aws.lixiangyun.top
  tls: client
channel:
  - protocol: tcp
    local: 127.0.0.1:8001
    remote: 127.0.0.1:8001
  - protocol: udp
    local: 127.0.0.1:8002
    remote: 127.0.0.1:8002
tls:
  - name: client
    ca: ./crt/ca.crt
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server
    ca: crt/ca.crt
    key: ./crt/server.pem
    cert: ./crt/server.crt