server:
  address: 0.0.0.0:38080
  tls: server
client:
  address: 127.0.0.1:38080
  tls: client
channel:
  - protocol: tcp
    local: 0.0.0.0:808
    remote: 10.173.164.213:8080
tls:
  - name: client
    ca: ./crt/ca.crt
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server
    ca: crt/ca.crt
    key: ./crt/server.pem
    cert: ./crt/server.crt