server:
  address: 0.0.0.0:8080
  tls: server
client:
  address: 127.0.0.1:8080
  tls: client
channel:
  - protocol: tcp
    local: 127.0.0.1:8002
    remote: 127.0.0.1:8082
tls:
  - name: client
    ca: ./crt/ca.crt
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server
    ca: crt/ca.crt
    key: ./crt/server.pem
    cert: ./crt/server.crt